import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Sessionwrapper from "./components/sessionwrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Donut - An Exclusice communty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Sessionwrapper>
          <Navbar/>
          <div className="min-h-screen bg-[radial-gradient(125%_125%_at_50%_10%,#000000_40%,#0d1a36_100%)]">

            {children}
          </div>
          <Footer />
        </Sessionwrapper>
      </body>
    </html>
  );
}
